version: '3.8'

services:
  app:
    build: .
    ports:
      - "9022:3000"  # 将容器的3000端口映射到主机的9022端口
    environment:
      NEXT_PUBLIC_ENVIRONMENT: "production"
      NEXT_PUBLIC_API_URL: "http://124.221.36.241:9021"
    volumes:
      - .:/app
    command: npm start
